// 시드 데이터 — 선배 + 데모 동기 + 후기 + 동료 신청 주제
const SENIORS = [
  { id:'park', name:'박민서', initial:'박', dept:'세무본부 (Tax)', years:15, loc:'강남오피스', rating:4.9,
    c1:'#E8775A', c2:'#F5A98A', lvl:'멘토 인증', email:'minseo.park@samil.example.com',
    tags:['#이전가격','#법인세','#15년차','#리더십'], hot:'#법인세', accept_rate:0.7,
    bio:"국내 대기업 이전가격 자문을 이끄는 <b>세무본부 디렉터</b>. 신입 시절 '질문하는 용기'가 커리어를 바꿨다고 믿어요. 합격 직후 입사를 앞둔 그 시기를 누구보다 잘 압니다.",
    topics:[['합격 후 입사 전, 무엇을 준비할까','선배가 추천하는 이 시기의 준비'],['세무 실무에서 진짜 쓰는 역량','시험 지식과 실무의 간극 좁히기'],['Tax 영역 커리어 패스','감사 vs 세무 vs 컨설팅, 무엇이 맞을까']] },
  { id:'kim', name:'김도윤', initial:'김', dept:'감사1본부 (Audit)', years:8, loc:'을지로오피스', rating:4.7,
    c1:'#5B8DEF', c2:'#8FB4F7', lvl:'네트워커', email:'doyun.kim@samil.example.com',
    tags:['#제조업감사','#IFRS','#8년차','#멘토링'], hot:'#IFRS', accept_rate:0.85,
    bio:'제조·중공업 상장사 감사를 담당하는 <b>인차지 시니어</b>. 동기 네트워킹으로 버틴 주니어 시절을 기억해, 후배 커피챗 신청은 거의 다 받아줍니다.',
    topics:[['입사 첫 달, 무엇을 준비할까','감사 시즌 전 미리 익혀두면 좋은 것'],['인차지가 보는 좋은 주니어','평가받는 핵심 태도와 협업 방식'],['워라밸과 시즌 생존법','바쁜 시즌을 버티는 현실적인 팁']] },
  { id:'lee', name:'이수아', initial:'이', dept:'Deals (재무자문)', years:11, loc:'강남오피스', rating:4.8,
    c1:'#9B6BD6', c2:'#C19BEC', lvl:'멘토 인증', email:'sua.lee@samil.example.com',
    tags:['#M&A','#밸류에이션','#11년차','#딜클로징'], hot:'#M&A', accept_rate:0.6,
    bio:'크로스보더 M&A 딜을 다루는 <b>Deals 본부 시니어 매니저</b>. 숫자 너머의 비즈니스를 보는 눈을 길러준 선배들 덕에 성장했다고 말합니다.',
    topics:[['Deals 본부는 무슨 일을 하나','감사·세무와 다른 업무의 결'],['밸류에이션 첫걸음','실무에서 모델을 어떻게 쓰는지'],['딜 마감의 짜릿함','왜 이 일을 계속하는지']] },
  { id:'jung', name:'정하늘', initial:'정', dept:'Consulting (Digital)', years:6, loc:'여의도오피스', rating:4.6,
    c1:'#22A98A', c2:'#5FD3B8', lvl:'네트워커', email:'haneul.jung@samil.example.com',
    tags:['#디지털전환','#데이터','#6년차','#애자일'], hot:'#디지털전환', accept_rate:0.55,
    bio:'금융사 디지털 전환 프로젝트를 뛰는 <b>컨설팅 본부 컨설턴트</b>. AI·자동화 툴을 실무에 녹이는 걸 좋아해,
